version: "3.8"

services:
  db:
    image: postgres:12.3
    container_name: liveman_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=liveman_dev
    ports:
      - "5432:5432"
